export default Object.freeze({
    // MENTOR
    MENTOR_RECEIVES_SESSION_REQUEST: 15, //userAdjustable/////
    MENTOR_VERIFICATION: 20,/////
    AFTER_MENTOR_VERIFIED: 21,/////
    REMIND_MENTOR_TO_REVIEW_MENTEE: 28, //userAdjustable/////
    MENTOR_APPROVES_SESSION_FOR_MENTOR: 3, //userAdjustable /////
    CANCELLED_CALL_SESSION: 75, //userAdjustable /////
    // STUDENT
    STUDENT_CREATES_REVIEW: 0, //userAdjustable /////
    JOB_APPLICATION_STATUS_CHANGED: 8, //userAdjustable /////
    STUDENT_APPLIED_FOR_JOB: 11, //userAdjustable /////
    STUDENT_UPLOADED_DOCUMENT: 12, //userAdjustable /////
    STUDENT_DOCUMENT_APPROVED_BY_ADMIN: 13, ///////
    STUDENT_VERIFICATION: 18, /////
    AFTER_STUDENT_VERIFIED: 19,/////
    MENTOR_DECLINES_SESSION: 22, //userAdjustable /////
    REMIND_MENTEE_TO_REVIEW_MENTOR: 29, //userAdjustable /////
    INFO_ABOUT_SESSION: 30, /////
    MENTOR_APPROVES_SESSION_FOR_STUDENT: 31, // REMEMBER TO ALWAYS SEND THE STUDENT TIPS TEMPLATE  //userAdjustable /////
    REVIEW_IS_APPROVED_BY_ADMIN_FOR_STUDENT: 32, // REMEMBER TO ALWAYS SEND THE STUDENT TIPS TEMPLATE  //userAdjustable /////
    // COMPANY
    STUDENT_APPLIES_FOR_JOB: 5, //userAdjustable /////
    COMPANY_WAITS_FOR_APPROVAL_FROM_ADMIN_AFTER_PROFILE_UPDATE: 6,/////
    COMPANY_SIGN_UP: 9, /////
    COMPANY_VERIFICATION:33, /////
    COMPANY_UPDATED_JOB_POST: 14, //userAdjustable /////
    COMPANY_POSTED_JOB: 16, //userAdjustable /////
    JOB_APPROVED_BY_ADMIN: 26,/////
    COMPANY_APPROVED_BY_ADMIN: 27, /////
    REVIEW_IS_APPROVED_BY_ADMIN_FOR_COMPANY: 7, // FOR BOTH STUDENT AND COMPANY /////
    // INSTITUTION
    INSTITUTION_SIGN_UP: 10,/////
    INSTITUTION_APPROVED_BY_ADMIN: 17,/////
    INSTITUTION_WAITS_FOR_APPROVAL_FROM_ADMIN_AFTER_PROFILE_UPDATE: 24,/////
    // USER
    USER_CHANGED_PASSWORD: 1,/////
    MESSAGE_RECEIVED: 2, //userAdjustable /////
    PASSWORD_RESET: 23,////////
    // MENTOR AND STUDENT
    STUDENT_MENTOR_ACCOUNT_UPDATE: 25, //userAdjustable /////
});